.TH "Cache_s" 3 "Mon Nov 16 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cache_s \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "collSet \fBupdated\fP"
.br
.ti -1c
.RI "collSet \fBdeleted\fP"
.br
.ti -1c
.RI "collSet \fBtoUpdate\fP"
.br
.ti -1c
.RI "collSet \fBtoDelete\fP"
.br
.ti -1c
.RI "collMap \fBlocal\fP"
.br
.ti -1c
.RI "char \fBtopic\fP [1024]"
.br
.ti -1c
.RI "\fBdcrudShareableFactory\fP \fBfactory\fP"
.br
.ti -1c
.RI "dcrudIRepositoryFactory \fBnetwork\fP"
.br
.ti -1c
.RI "unsigned int \fBlastInstanceId\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file Cache\&.c\&.
.SH "Field Documentation"
.PP 
.SS "collSet deleted"

.PP
Definition at line 13 of file Cache\&.c\&.
.SS "\fBdcrudShareableFactory\fP factory"

.PP
Definition at line 18 of file Cache\&.c\&.
.SS "unsigned int lastInstanceId"

.PP
Definition at line 20 of file Cache\&.c\&.
.SS "collMap local"

.PP
Definition at line 16 of file Cache\&.c\&.
.SS "dcrudIRepositoryFactory network"

.PP
Definition at line 19 of file Cache\&.c\&.
.SS "collSet toDelete"

.PP
Definition at line 15 of file Cache\&.c\&.
.SS "char topic[1024]"

.PP
Definition at line 17 of file Cache\&.c\&.
.SS "collSet toUpdate"

.PP
Definition at line 14 of file Cache\&.c\&.
.SS "collSet updated"

.PP
Definition at line 12 of file Cache\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
