.TH "inc/util/check.h" 3 "Mon Nov 16 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/util/check.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <util/types\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcheck\fP (\fBbool\fP ok, const char *file, int line, const char *format,\&.\&.\&.)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void check (\fBbool\fPok, const char *file, intline, const char *format, \&.\&.\&.)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
