.TH "inc/dcrud/ClassID.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dcrud/ClassID.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <io/ByteBuffer\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBUTIL_ADT\fP (dcrudClassID)"
.br
.ti -1c
.RI "dcrudClassID \fBdcrudClassID_new\fP (\fBbyte\fP package1, \fBbyte\fP package2, \fBbyte\fP package3, \fBbyte\fP clazz)"
.br
.ti -1c
.RI "void \fBdcrudClassID_delete\fP (dcrudClassID *target)"
.br
.ti -1c
.RI "void \fBdcrudClassID_get\fP (const dcrudClassID This, \fBbyte\fP *pckg1, \fBbyte\fP *pckg2, \fBbyte\fP *pckg3, \fBbyte\fP *clazz)"
.br
.ti -1c
.RI "\fBioStatus\fP \fBdcrudClassID_unserialize\fP (ioByteBuffer source, dcrudClassID *target)"
.br
.ti -1c
.RI "\fBioStatus\fP \fBdcrudClassID_serialize\fP (const dcrudClassID This, ioByteBuffer target)"
.br
.ti -1c
.RI "\fBbool\fP \fBdcrudClassID_toString\fP (const dcrudClassID This, char *target, size_t targetSize)"
.br
.ti -1c
.RI "int \fBdcrudClassID_compareTo\fP (const dcrudClassID *left, const dcrudClassID *right)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int dcrudClassID_compareTo (const dcrudClassID *left, const dcrudClassID *right)"

.SS "void dcrudClassID_delete (dcrudClassID *target)"

.SS "void dcrudClassID_get (const dcrudClassIDThis, \fBbyte\fP *pckg1, \fBbyte\fP *pckg2, \fBbyte\fP *pckg3, \fBbyte\fP *clazz)"

.SS "dcrudClassID dcrudClassID_new (\fBbyte\fPpackage1, \fBbyte\fPpackage2, \fBbyte\fPpackage3, \fBbyte\fPclazz)"

.SS "\fBioStatus\fP dcrudClassID_serialize (const dcrudClassIDThis, ioByteBuffertarget)"

.SS "\fBbool\fP dcrudClassID_toString (const dcrudClassIDThis, char *target, size_ttargetSize)"

.SS "\fBioStatus\fP dcrudClassID_unserialize (ioByteBuffersource, dcrudClassID *target)"

.SS "UTIL_ADT (dcrudClassID)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
