.TH "collPrivateSet_s" 3 "Mon Nov 16 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
collPrivateSet_s \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBcount\fP"
.br
.ti -1c
.RI "unsigned \fBlimit\fP"
.br
.ti -1c
.RI "\fBcollSetItem\fP * \fBitems\fP"
.br
.ti -1c
.RI "\fBcollComparator\fP \fBcmp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file Set\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBcollComparator\fP cmp"

.PP
Definition at line 16 of file Set\&.c\&.
.SS "unsigned count"

.PP
Definition at line 9 of file Set\&.c\&.
.SS "\fBcollSetItem\fP* items"

.PP
Definition at line 14 of file Set\&.c\&.
.SS "unsigned limit"

.PP
Definition at line 13 of file Set\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
