.TH "collForeach_s" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
collForeach_s \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ForeachFunction\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBindex\fP"
.br
.ti -1c
.RI "void * \fBitem\fP"
.br
.ti -1c
.RI "void * \fBuser\fP"
.br
.ti -1c
.RI "\fBcollForeachResult\fP \fBretVal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file ForeachFunction\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int index"

.PP
Definition at line 7 of file ForeachFunction\&.h\&.
.SS "void* item"

.PP
Definition at line 8 of file ForeachFunction\&.h\&.
.SS "\fBcollForeachResult\fP retVal"

.PP
Definition at line 10 of file ForeachFunction\&.h\&.
.SS "void* user"

.PP
Definition at line 9 of file ForeachFunction\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
