.TH "collForeachMap_s" 3 "Mon Nov 16 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
collForeachMap_s \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Map\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBindex\fP"
.br
.ti -1c
.RI "\fBcollMapKey\fP \fBkey\fP"
.br
.ti -1c
.RI "\fBcollMapValue\fP \fBvalue\fP"
.br
.ti -1c
.RI "void * \fBuser\fP"
.br
.ti -1c
.RI "\fBcollForeachMapResult\fP \fBretVal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file Map\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int index"

.PP
Definition at line 13 of file Map\&.h\&.
.SS "\fBcollMapKey\fP key"

.PP
Definition at line 14 of file Map\&.h\&.
.SS "\fBcollForeachMapResult\fP retVal"

.PP
Definition at line 17 of file Map\&.h\&.
.SS "void* user"

.PP
Definition at line 16 of file Map\&.h\&.
.SS "\fBcollMapValue\fP value"

.PP
Definition at line 15 of file Map\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
