.TH "collMapPair_s" 3 "Mon Nov 16 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
collMapPair_s \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBcollMapKey\fP \fBkey\fP"
.br
.ti -1c
.RI "\fBcollMapValue\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file Map\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBcollMapKey\fP key"

.PP
Definition at line 9 of file Map\&.c\&.
.SS "\fBcollMapValue\fP value"

.PP
Definition at line 10 of file Map\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
