.TH "collPrivateList_s" 3 "Mon Nov 16 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
collPrivateList_s \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBcount\fP"
.br
.ti -1c
.RI "unsigned \fBlimit\fP"
.br
.ti -1c
.RI "\fBcollListItem\fP * \fBitems\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file List\&.c\&.
.SH "Field Documentation"
.PP 
.SS "unsigned count"

.PP
Definition at line 9 of file List\&.c\&.
.SS "\fBcollListItem\fP* items"

.PP
Definition at line 14 of file List\&.c\&.
.SS "unsigned limit"

.PP
Definition at line 13 of file List\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
