.TH "collPrivateMap_s" 3 "Mon Nov 16 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
collPrivateMap_s \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBcollComparator\fP \fBcmp\fP"
.br
.ti -1c
.RI "unsigned \fBcount\fP"
.br
.ti -1c
.RI "unsigned \fBlimit\fP"
.br
.ti -1c
.RI "\fBcollMapPair\fP * \fBpairs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file Map\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBcollComparator\fP cmp"

.PP
Definition at line 16 of file Map\&.c\&.
.SS "unsigned count"

.PP
Definition at line 17 of file Map\&.c\&.
.SS "unsigned limit"

.PP
Definition at line 21 of file Map\&.c\&.
.SS "\fBcollMapPair\fP* pairs"

.PP
Definition at line 22 of file Map\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
