.TH "inc/coll/Comparator.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/coll/Comparator.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int(* \fBcollComparator\fP )(const void *left, const void *right)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcollStringComparator\fP (const char **left, const char **right)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef int( *  collComparator)(const void *left, const void *right)"

.PP
Definition at line 3 of file Comparator\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int collStringComparator (const char **left, const char **right)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
