.TH "dcrudGUIDImpl_s" 3 "Mon Nov 16 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dcrudGUIDImpl_s \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBtopic\fP [1024]"
.br
.ti -1c
.RI "int \fBclassId\fP"
.br
.ti -1c
.RI "int \fBinstance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file GUID\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int classId"

.PP
Definition at line 8 of file GUID\&.c\&.
.SS "int instance"

.PP
Definition at line 9 of file GUID\&.c\&.
.SS "char topic[1024]"

.PP
Definition at line 7 of file GUID\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
