.TH "dcrudShareableImpl_s" 3 "Mon Nov 16 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dcrudShareableImpl_s \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBdcrudSerializable\fP \fBserializable\fP"
.br
.ti -1c
.RI "dcrudGUID \fBid\fP"
.br
.ti -1c
.RI "\fBdcrudShareable_setF\fP \fBset\fP"
.br
.ti -1c
.RI "\fBdcrudShareable_serializeF\fP \fBserialize\fP"
.br
.ti -1c
.RI "\fBdcrudShareable_unserializeF\fP \fBunserialize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file Shareable\&.c\&.
.SH "Field Documentation"
.PP 
.SS "dcrudGUID id"

.PP
Definition at line 6 of file Shareable\&.c\&.
.SS "\fBdcrudSerializable\fP serializable"

.PP
Definition at line 5 of file Shareable\&.c\&.
.SS "\fBdcrudShareable_serializeF\fP serialize"

.PP
Definition at line 8 of file Shareable\&.c\&.
.SS "\fBdcrudShareable_setF\fP set"

.PP
Definition at line 7 of file Shareable\&.c\&.
.SS "\fBdcrudShareable_unserializeF\fP unserialize"

.PP
Definition at line 9 of file Shareable\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
