.TH "inc/dbg/Dump.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dbg/Dump.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <util/types\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdbgDump_range\fP (FILE *target, const \fBbyte\fP *buffer, size_t from, size_t to)"
.br
.ti -1c
.RI "void \fBdbgDump\fP (FILE *target, const \fBbyte\fP *buffer, size_t length)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void dbgDump (FILE *target, const \fBbyte\fP *buffer, size_tlength)"

.SS "void dbgDump_range (FILE *target, const \fBbyte\fP *buffer, size_tfrom, size_tto)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
