.TH "inc/coll/ForeachFunction.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/coll/ForeachFunction.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBcollForeach_s\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBcollForeachResult\fP"
.br
.ti -1c
.RI "typedef struct \fBcollForeach_s\fP \fBcollForeach\fP"
.br
.ti -1c
.RI "typedef \fBbool\fP(* \fBcollForeachFunction\fP )(\fBcollForeach\fP *context)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBcollForeach_s\fP  \fBcollForeach\fP"

.SS "typedef \fBbool\fP( *  collForeachFunction)(\fBcollForeach\fP *context)"

.PP
Definition at line 14 of file ForeachFunction\&.h\&.
.SS "typedef void* \fBcollForeachResult\fP"

.PP
Definition at line 3 of file ForeachFunction\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
