.TH "inc/dcrud/GUID.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dcrud/GUID.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <io/ByteBuffer\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBUTIL_ADT\fP (dcrudGUID)"
.br
.ti -1c
.RI "\fBioStatus\fP \fBdcrudGUID_unserialize\fP (ioByteBuffer source, dcrudGUID *target)"
.br
.ti -1c
.RI "\fBioStatus\fP \fBdcrudGUID_serialize\fP (const dcrudGUID This, ioByteBuffer target)"
.br
.ti -1c
.RI "\fBbool\fP \fBdcrudGUID_toString\fP (const dcrudGUID This, char *target, size_t targetSize)"
.br
.ti -1c
.RI "int \fBdcrudGUID_compareTo\fP (const dcrudGUID *left, const dcrudGUID *right)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int dcrudGUID_compareTo (const dcrudGUID *left, const dcrudGUID *right)"

.SS "\fBioStatus\fP dcrudGUID_serialize (const dcrudGUIDThis, ioByteBuffertarget)"

.SS "\fBbool\fP dcrudGUID_toString (const dcrudGUIDThis, char *target, size_ttargetSize)"

.SS "\fBioStatus\fP dcrudGUID_unserialize (ioByteBuffersource, dcrudGUID *target)"

.SS "UTIL_ADT (dcrudGUID)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
