.TH "inc/dcrud/ICache.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dcrud/ICache.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <coll/Map\&.h>\fP
.br
\fC#include <dcrud/Shareable\&.h>\fP
.br
\fC#include <dcrud/Status\&.h>\fP
.br
\fC#include <coll/Set\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBbool\fP(* \fBdcrudPredicate\fP )(dcrudShareable item)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBUTIL_ADT\fP (dcrudICache)"
.br
.ti -1c
.RI "void \fBdcrudICache_setOwnership\fP (dcrudICache This, \fBbool\fP enabled)"
.br
.ti -1c
.RI "\fBbool\fP \fBdcrudICache_owns\fP (dcrudICache This, dcrudGUID id)"
.br
.ti -1c
.RI "\fBdcrudStatus\fP \fBdcrudICache_create\fP (dcrudICache This, dcrudShareable item)"
.br
.ti -1c
.RI "dcrudShareable \fBdcrudICache_read\fP (dcrudICache This, dcrudGUID id)"
.br
.ti -1c
.RI "\fBdcrudStatus\fP \fBdcrudICache_update\fP (dcrudICache This, dcrudShareable item)"
.br
.ti -1c
.RI "\fBdcrudStatus\fP \fBdcrudICache_delete\fP (dcrudICache This, dcrudShareable item)"
.br
.ti -1c
.RI "\fBcollForeachResult\fP \fBdcrudICache_foreach\fP (dcrudICache This, \fBcollForeachFunction\fP fn, void *userData)"
.br
.ti -1c
.RI "collSet \fBdcrudICache_select\fP (dcrudICache This, \fBdcrudPredicate\fP query)"
.br
.ti -1c
.RI "\fBdcrudStatus\fP \fBdcrudICache_publish\fP (dcrudICache This)"
.br
.ti -1c
.RI "void \fBdcrudICache_subscribe\fP (dcrudICache This, dcrudClassID id)"
.br
.ti -1c
.RI "void \fBdcrudICache_refresh\fP (dcrudICache This)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBbool\fP( *  dcrudPredicate)(dcrudShareable item)"

.PP
Definition at line 10 of file ICache\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBdcrudStatus\fP dcrudICache_create (dcrudICacheThis, dcrudShareableitem)"

.SS "\fBdcrudStatus\fP dcrudICache_delete (dcrudICacheThis, dcrudShareableitem)"

.SS "\fBcollForeachResult\fP dcrudICache_foreach (dcrudICacheThis, \fBcollForeachFunction\fPfn, void *userData)"

.SS "\fBbool\fP dcrudICache_owns (dcrudICacheThis, dcrudGUIDid)"

.SS "\fBdcrudStatus\fP dcrudICache_publish (dcrudICacheThis)"

.SS "dcrudShareable dcrudICache_read (dcrudICacheThis, dcrudGUIDid)"

.SS "void dcrudICache_refresh (dcrudICacheThis)"

.SS "collSet dcrudICache_select (dcrudICacheThis, \fBdcrudPredicate\fPquery)"

.SS "void dcrudICache_setOwnership (dcrudICacheThis, \fBbool\fPenabled)"

.SS "void dcrudICache_subscribe (dcrudICacheThis, dcrudClassIDid)"

.SS "\fBdcrudStatus\fP dcrudICache_update (dcrudICacheThis, dcrudShareableitem)"

.SS "UTIL_ADT (dcrudICache)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
