.TH "inc/dcrud/ICallback.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dcrud/ICallback.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <coll/Map\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBdcrudICallback_function\fP )(dcrudICallback This, const char *intrfc, const char *operation, collMap results)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBUTIL_ADT\fP (dcrudICallback)"
.br
.ti -1c
.RI "dcrudICallback \fBdcrudICallback_new\fP (\fBdcrudICallback_function\fP callback, void *userData)"
.br
.ti -1c
.RI "void \fBdcrudICallback_delete\fP (dcrudICallback *This)"
.br
.ti -1c
.RI "void \fBdcrudICallback_callback\fP (dcrudICallback This, const char *intrfc, const char *operation, collMap results)"
.br
.ti -1c
.RI "void * \fBdcrudICallback_getUserData\fP (dcrudICallback This)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void(*  dcrudICallback_function)(dcrudICallback This, const char *intrfc, const char *operation, collMap results)"

.PP
Definition at line 6 of file ICallback\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void dcrudICallback_callback (dcrudICallbackThis, const char *intrfc, const char *operation, collMapresults)"

.SS "void dcrudICallback_delete (dcrudICallback *This)"

.SS "void* dcrudICallback_getUserData (dcrudICallbackThis)"

.SS "dcrudICallback dcrudICallback_new (\fBdcrudICallback_function\fPcallback, void *userData)"

.SS "UTIL_ADT (dcrudICallback)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
