.TH "inc/dcrud/IDispatcher.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dcrud/IDispatcher.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <coll/Map\&.h>\fP
.br
\fC#include <dcrud/Shareable\&.h>\fP
.br
\fC#include <dcrud/Status\&.h>\fP
.br
\fC#include <dcrud/IProvided\&.h>\fP
.br
\fC#include <dcrud/IRequired\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBUTIL_ADT\fP (dcrudIDispatcher)"
.br
.ti -1c
.RI "dcrudIProvided \fBdcrudIDispatcher_provide\fP (dcrudIDispatcher This, const char *name)"
.br
.ti -1c
.RI "dcrudIRequired \fBdcrudIDispatcher_require\fP (dcrudIDispatcher This, const char *name)"
.br
.ti -1c
.RI "void \fBdcrudIDispatcher_handleRequests\fP (dcrudIDispatcher This)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void dcrudIDispatcher_handleRequests (dcrudIDispatcherThis)"

.SS "dcrudIProvided dcrudIDispatcher_provide (dcrudIDispatcherThis, const char *name)"

.SS "dcrudIRequired dcrudIDispatcher_require (dcrudIDispatcherThis, const char *name)"

.SS "UTIL_ADT (dcrudIDispatcher)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
