.TH "inc/dcrud/IParticipant.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dcrud/IParticipant.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dcrud/ICache\&.h>\fP
.br
\fC#include <dcrud/IDispatcher\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef dcrudShareable(* \fBdcrudShareableFactory\fP )()"
.br
.ti -1c
.RI "typedef void(* \fBdcrudShareable_Set\fP )(\fBdcrudShareableData\fP This, const \fBdcrudShareableData\fP source)"
.br
.ti -1c
.RI "typedef \fBioStatus\fP(* \fBdcrudShareable_Serialize\fP )(\fBdcrudShareableData\fP This, ioByteBuffer target)"
.br
.ti -1c
.RI "typedef \fBioStatus\fP(* \fBdcrudShareable_Unserialize\fP )(\fBdcrudShareableData\fP This, ioByteBuffer source)"
.br
.ti -1c
.RI "typedef \fBbool\fP(* \fBdcrudShareable_Initialize\fP )(\fBdcrudShareableData\fP This)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBUTIL_ADT\fP (dcrudIParticipant)"
.br
.ti -1c
.RI "\fBbool\fP \fBdcrudIParticipant_registerClass\fP (dcrudIParticipant This, dcrudClassID id, size_t size, \fBdcrudShareable_Initialize\fP initialize, \fBdcrudShareable_Set\fP set, \fBdcrudShareable_Serialize\fP serialize, \fBdcrudShareable_Unserialize\fP unserialize)"
.br
.ti -1c
.RI "\fBdcrudStatus\fP \fBdcrudIParticipant_createCache\fP (dcrudIParticipant This, dcrudICache *target)"
.br
.ti -1c
.RI "dcrudICache \fBdcrudIParticipant_getCache\fP (dcrudIParticipant This, \fBbyte\fP ID)"
.br
.ti -1c
.RI "dcrudIDispatcher \fBdcrudIParticipant_getDispatcher\fP (dcrudIParticipant This)"
.br
.ti -1c
.RI "dcrudShareable \fBdcrudIParticipant_createShareable\fP (dcrudIParticipant This, dcrudClassID classID)"
.br
.ti -1c
.RI "void \fBdcrudIParticipant_run\fP (dcrudIParticipant This)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBbool\fP(*  dcrudShareable_Initialize)(\fBdcrudShareableData\fP This)"

.PP
Definition at line 12 of file IParticipant\&.h\&.
.SS "typedef \fBioStatus\fP(*  dcrudShareable_Serialize)(\fBdcrudShareableData\fP This, ioByteBuffer target)"

.PP
Definition at line 10 of file IParticipant\&.h\&.
.SS "typedef void(*  dcrudShareable_Set)(\fBdcrudShareableData\fP This, const \fBdcrudShareableData\fP source)"

.PP
Definition at line 9 of file IParticipant\&.h\&.
.SS "typedef \fBioStatus\fP(*  dcrudShareable_Unserialize)(\fBdcrudShareableData\fP This, ioByteBuffer source)"

.PP
Definition at line 11 of file IParticipant\&.h\&.
.SS "typedef dcrudShareable(*  dcrudShareableFactory)()"

.PP
Definition at line 5 of file IParticipant\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBdcrudStatus\fP dcrudIParticipant_createCache (dcrudIParticipantThis, dcrudICache *target)"

.SS "dcrudShareable dcrudIParticipant_createShareable (dcrudIParticipantThis, dcrudClassIDclassID)"

.SS "dcrudICache dcrudIParticipant_getCache (dcrudIParticipantThis, \fBbyte\fPID)"

.SS "dcrudIDispatcher dcrudIParticipant_getDispatcher (dcrudIParticipantThis)"

.SS "\fBbool\fP dcrudIParticipant_registerClass (dcrudIParticipantThis, dcrudClassIDid, size_tsize, \fBdcrudShareable_Initialize\fPinitialize, \fBdcrudShareable_Set\fPset, \fBdcrudShareable_Serialize\fPserialize, \fBdcrudShareable_Unserialize\fPunserialize)"

.SS "void dcrudIParticipant_run (dcrudIParticipantThis)"

.SS "UTIL_ADT (dcrudIParticipant)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
