.TH "inc/dcrud/IProvided.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dcrud/IProvided.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBdcrudIOperation\fP )(void *context, collMap in, collMap out)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBUTIL_ADT\fP (dcrudIProvided)"
.br
.ti -1c
.RI "\fBbool\fP \fBdcrudIProvided_addOperation\fP (dcrudIProvided provided, const char *name, void *context, \fBdcrudIOperation\fP operation)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void(*  dcrudIOperation)(void *context, collMap in, collMap out)"

.PP
Definition at line 5 of file IProvided\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBbool\fP dcrudIProvided_addOperation (dcrudIProvidedprovided, const char *name, void *context, \fBdcrudIOperation\fPoperation)"

.SS "UTIL_ADT (dcrudIProvided)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
