.TH "inc/dcrud/IRepository.h" 3 "Mon Nov 16 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dcrud/IRepository.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <coll/Map\&.h>\fP
.br
\fC#include <dcrud/Shareable\&.h>\fP
.br
\fC#include <dcrud/Errors\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBUTIL_ADT\fP (dcrudIRepository)"
.br
.ti -1c
.RI "\fBdcrudErrorCode\fP \fBdcrudIRepository_create\fP (dcrudIRepository This, dcrudShareable item)"
.br
.ti -1c
.RI "dcrudShareable * \fBdcrudIRepository_read\fP (dcrudIRepository This, dcrudGUID id)"
.br
.ti -1c
.RI "\fBdcrudErrorCode\fP \fBdcrudIRepository_update\fP (dcrudIRepository This, dcrudShareable item)"
.br
.ti -1c
.RI "\fBdcrudErrorCode\fP \fBdcrudIRepository_delete\fP (dcrudIRepository This, dcrudShareable item)"
.br
.ti -1c
.RI "collMap \fBdcrudIRepository_getAll\fP (dcrudIRepository This)"
.br
.ti -1c
.RI "\fBbool\fP \fBdcrudIRepository_isProducer\fP (dcrudIRepository This)"
.br
.ti -1c
.RI "\fBbool\fP \fBdcrudIRepository_isConsumer\fP (dcrudIRepository This)"
.br
.ti -1c
.RI "\fBdcrudErrorCode\fP \fBdcrudIRepository_publish\fP (dcrudIRepository This)"
.br
.ti -1c
.RI "\fBdcrudErrorCode\fP \fBdcrudIRepository_refresh\fP (dcrudIRepository This)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBdcrudErrorCode\fP dcrudIRepository_create (dcrudIRepositoryThis, dcrudShareableitem)"

.SS "\fBdcrudErrorCode\fP dcrudIRepository_delete (dcrudIRepositoryThis, dcrudShareableitem)"

.SS "collMap dcrudIRepository_getAll (dcrudIRepositoryThis)"

.SS "\fBbool\fP dcrudIRepository_isConsumer (dcrudIRepositoryThis)"

.SS "\fBbool\fP dcrudIRepository_isProducer (dcrudIRepositoryThis)"

.SS "\fBdcrudErrorCode\fP dcrudIRepository_publish (dcrudIRepositoryThis)"

.SS "dcrudShareable* dcrudIRepository_read (dcrudIRepositoryThis, dcrudGUIDid)"

.SS "\fBdcrudErrorCode\fP dcrudIRepository_refresh (dcrudIRepositoryThis)"

.SS "\fBdcrudErrorCode\fP dcrudIRepository_update (dcrudIRepositoryThis, dcrudShareableitem)"

.SS "UTIL_ADT (dcrudIRepository)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
