.TH "inc/coll/Map.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/coll/Map.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <util/types\&.h>\fP
.br
\fC#include <coll/Map\&.template>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCOLL_MAP_TYPE\fP   collMap"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBUTIL_CONCAT\fP (\fBCOLL_MAP_TYPE\fP, Value)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COLL_MAP_TYPE   collMap"

.PP
Definition at line 5 of file Map\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef void* UTIL_CONCAT(\fBCOLL_MAP_TYPE\fP, Value)"

.PP
Definition at line 6 of file Map\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
