.TH "inc/coll/MapFuncPtr.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/coll/MapFuncPtr.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <util/types\&.h>\fP
.br
\fC#include <coll/Map\&.template>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCOLL_MAP_TYPE\fP   collMapFuncPtr"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(*)(void * \fBUTIL_CONCAT\fP )(\fBCOLL_MAP_TYPE\fP, Value)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COLL_MAP_TYPE   collMapFuncPtr"

.PP
Definition at line 6 of file MapFuncPtr\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* )( void *  UTIL_CONCAT)(\fBCOLL_MAP_TYPE\fP, Value)"

.PP
Definition at line 7 of file MapFuncPtr\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
