.TH "inc/os/Mutex.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/os/Mutex.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <util/types\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBUTIL_ADT\fP (osMutex)"
.br
.ti -1c
.RI "int \fBosMutex_new\fP (osMutex *This)"
.br
.ti -1c
.RI "int \fBosMutex_delete\fP (osMutex *This)"
.br
.ti -1c
.RI "int \fBosMutex_take\fP (osMutex This)"
.br
.ti -1c
.RI "int \fBosMutex_release\fP (osMutex This)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int osMutex_delete (osMutex *This)"

.SS "int osMutex_new (osMutex *This)"

.SS "int osMutex_release (osMutexThis)"

.SS "int osMutex_take (osMutexThis)"

.SS "UTIL_ADT (osMutex)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
