.TH "inc/dcrud/Network.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dcrud/Network.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dcrud/IParticipant\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "dcrudIParticipant \fBdcrudNetwork_join\fP (const char *networkConfFile, const char *intrfc, unsigned short id)"
.br
.ti -1c
.RI "void \fBdcrudNetwork_leave\fP (dcrudIParticipant *This)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "dcrudIParticipant dcrudNetwork_join (const char *networkConfFile, const char *intrfc, unsigned shortid)"

.SS "void dcrudNetwork_leave (dcrudIParticipant *This)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
