.TH "inc/util/Perf.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/util/Perf.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <util/types\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fButilPerf_enable\fP (\fBbool\fP enabled)"
.br
.ti -1c
.RI "void \fButilPerf_record\fP (const char *attribute, uint64_t elapsed)"
.br
.ti -1c
.RI "void \fButilPerf_display\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void utilPerf_display ()"

.SS "void utilPerf_enable (\fBbool\fPenabled)"

.SS "void utilPerf_record (const char *attribute, uint64_telapsed)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
