.TH "inc/dbg/Performance.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dbg/Performance.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <util/types\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdbgPerformance_enable\fP (\fBbool\fP enabled)"
.br
.ti -1c
.RI "void \fBdbgPerformance_record\fP (const char *attribute, uint64_t elapsed)"
.br
.ti -1c
.RI "void \fBdbgPerformance_saveToDisk\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void dbgPerformance_enable (\fBbool\fPenabled)"

.SS "void dbgPerformance_record (const char *attribute, uint64_telapsed)"

.SS "void dbgPerformance_saveToDisk (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
