.TH "Repositories_s" 3 "Mon Nov 16 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Repositories_s \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "SOCKET \fBsckt\fP"
.br
.ti -1c
.RI "struct sockaddr_in \fBtarget\fP"
.br
.ti -1c
.RI "collMap \fBrepositories\fP"
.br
.ti -1c
.RI "ioByteBuffer \fBheader\fP"
.br
.ti -1c
.RI "ioByteBuffer \fBpayload\fP"
.br
.ti -1c
.RI "ioByteBuffer \fBframe\fP"
.br
.ti -1c
.RI "unsigned \fBid\fP"
.br
.ti -1c
.RI "unsigned \fBmessageCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file Repositories\&.c\&.
.SH "Field Documentation"
.PP 
.SS "ioByteBuffer frame"

.PP
Definition at line 22 of file Repositories\&.c\&.
.SS "ioByteBuffer header"

.PP
Definition at line 20 of file Repositories\&.c\&.
.SS "unsigned id"

.PP
Definition at line 23 of file Repositories\&.c\&.
.SS "unsigned messageCount"

.PP
Definition at line 24 of file Repositories\&.c\&.
.SS "ioByteBuffer payload"

.PP
Definition at line 21 of file Repositories\&.c\&.
.SS "collMap repositories"

.PP
Definition at line 19 of file Repositories\&.c\&.
.SS "SOCKET sckt"

.PP
Definition at line 17 of file Repositories\&.c\&.
.SS "struct sockaddr_in target"

.PP
Definition at line 18 of file Repositories\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
