.TH "inc/dcrud/RepositoryFactoryBuilder.h" 3 "Mon Nov 16 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dcrud/RepositoryFactoryBuilder.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dcrud/IRepositoryFactory\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "dcrudIRepositoryFactory \fBdcrudRepositoryFactoryBuilder_join\fP (const char *address, const char *intrfc, unsigned short port, unsigned int id)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "dcrudIRepositoryFactory dcrudRepositoryFactoryBuilder_join (const char *address, const char *intrfc, unsigned shortport, unsigned intid)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
