.TH "inc/io/Status.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/io/Status.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBioStatus_e\fP \fBioStatus\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBioStatus_e\fP { \fBIO_STATUS_NO_ERROR\fP, \fBIO_STATUS_OVERFLOW\fP, \fBIO_STATUS_UNDERFLOW\fP, \fBIO_STATUS_NO_MARK\fP, \fBIO_STATUS_SENDTO_FAILED\fP, \fBIO_STATUS_RECV_FAILED\fP, \fBIO_STATUS_LAST\fP }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char * \fBioStatusMessages\fP [\fBIO_STATUS_LAST\fP]"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef enum \fBioStatus_e\fP  \fBioStatus\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBioStatus_e\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIIO_STATUS_NO_ERROR \fP\fP
.TP
\fB\fIIO_STATUS_OVERFLOW \fP\fP
.TP
\fB\fIIO_STATUS_UNDERFLOW \fP\fP
.TP
\fB\fIIO_STATUS_NO_MARK \fP\fP
.TP
\fB\fIIO_STATUS_SENDTO_FAILED \fP\fP
.TP
\fB\fIIO_STATUS_RECV_FAILED \fP\fP
.TP
\fB\fIIO_STATUS_LAST \fP\fP
.PP
Definition at line 3 of file Status\&.h\&.
.PP
.nf
3                         {
4 
5    IO_STATUS_NO_ERROR,
6    IO_STATUS_OVERFLOW,        /* relative to put operations */
7    IO_STATUS_UNDERFLOW,       /* relative to get operations */
8    IO_STATUS_NO_MARK,         /* reset() called without previous call to mark() */
9    IO_STATUS_SENDTO_FAILED,
10    IO_STATUS_RECV_FAILED,
11 
12    IO_STATUS_LAST
13 
14 } ioStatus;
.fi
.SH "Variable Documentation"
.PP 
.SS "const char* ioStatusMessages[\fBIO_STATUS_LAST\fP]"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
