.TH "inc/os/System.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/os/System.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <util/types\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint64_t \fBosSystem_nanotime\fP (void)"
.br
.ti -1c
.RI "\fBbool\fP \fBosSystem_sleep\fP (unsigned int milliseconds)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint64_t osSystem_nanotime (void)"

.SS "\fBbool\fP osSystem_sleep (unsigned intmilliseconds)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
