.TH "inc/util/types.h" 3 "Wed Dec 9 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/util/types.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBfalse\fP   0"
.br
.ti -1c
.RI "#define \fBtrue\fP   (!\fBfalse\fP)"
.br
.ti -1c
.RI "#define \fBUTIL_CONCAT_\fP(x, y)   x ## y"
.br
.ti -1c
.RI "#define \fBUTIL_CONCAT\fP(x, y)   \fBUTIL_CONCAT_\fP(x,y)"
.br
.ti -1c
.RI "#define \fBUTIL_ADT\fP(T)   typedef struct \fBUTIL_CONCAT\fP(T,_s) { int unused; } * T"
.br
.ti -1c
.RI "#define \fBUTIL_CAST\fP(T, P)   ((T)(P))"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBbool\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBbyte\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define false   0"

.PP
Definition at line 7 of file types\&.h\&.
.SS "#define true   (!\fBfalse\fP)"

.PP
Definition at line 8 of file types\&.h\&.
.SS "#define UTIL_ADT(T)   typedef struct \fBUTIL_CONCAT\fP(T,_s) { int unused; } * T"

.PP
Definition at line 19 of file types\&.h\&.
.SS "#define UTIL_CAST(T, P)   ((T)(P))"

.PP
Definition at line 20 of file types\&.h\&.
.SS "#define UTIL_CONCAT(x, y)   \fBUTIL_CONCAT_\fP(x,y)"

.PP
Definition at line 18 of file types\&.h\&.
.SS "#define UTIL_CONCAT_(x, y)   x ## y"

.PP
Definition at line 17 of file types\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef int \fBbool\fP"

.PP
Definition at line 6 of file types\&.h\&.
.SS "typedef unsigned char \fBbyte\fP"

.PP
Definition at line 11 of file types\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
